### ISSUE TITLE
HTTP profile missing 'kill date' field

### ISSUE THREAD

**Issue by timukas** [MythicC2Profiles/http#12]
Hello,

On latest version of Mythic 'kill date' field is missing in HTTP profile settings page:

![image](https://github.com/MythicC2Profiles/http/assets/1915618/5d1a7513-100d-46a1-965b-100408af863b)

**Comment by its-a-feature** [comment]
Thanks for noticing that! I Just updated the Mythic server to fix the UI component for it

**Comment by timukas** [comment]
Yes, now killdate field is there.
