### ISSUE TITLE
Failing running 'make run' due to permissions

### ISSUE THREAD

**Issue by ts-lbf** [MythicC2Profiles/http#13]
Hi,
I am trying to install this profile using the command
`sudo ./mythic-cli install github https://github.com/MythicC2Profiles/http`
But the http container keeps dying.
I took a close look at the log output and got the following:
> cp /main . 
> cp: can't create './main': Permission denied
> make: *** [Makefile:19: run] Error 1

So it seems like running the `make run`command errors because it tries to copy main and it does not have permissions. I tried to add permission and using `USER root` but without luck.

**Comment by its-a-feature** [comment]
What OS are you running this on? I don't think i've seen that one before

**Comment by ts-lbf** [comment]
I am running on macOS and using OrbStack

**Comment by its-a-feature** [comment]
weird, i just ran it without issue on macOS with OrbStack. What version of macOS and intel or arm?

**Comment by ts-lbf** [comment]
Running Sonoma 14.0 and the M2 processor (arm)

**Comment by its-a-feature** [comment]
The Mythic server is up and running for you though? It should be along the same process of building a binary and copying it. Also, are you running mythic-cli as root or as your normal user? With orbstack, I think you can just run everything as a normal user, but I wonder if something about that is causing an issue?

**Comment by ts-lbf** [comment]
I have installed the DNS profile and apfell agent, but i discovered problems with the websocket profile as well as the freyja agent

the log from freyja:
> cp /main .
> cp: cannot create regular file './main': Permission denied
> make: *** [Makefile:20: run] Error 1

the log from websocket:
> cd websocket/c2_code && make run
> make[1]: Entering directory '/Mythic/websocket/c2_code'
> cp /mythic_websocket_server .
> cp: cannot create regular file './mythic_websocket_server': Permission denied
> make[1]: *** [Makefile:22: run] Error 1
> make: *** [Makefile:17: run] Error 2
> make[1]: Leaving directory '/Mythic/websocket/c2_code'

**Comment by ts-lbf** [comment]
Never mind i also have problems with the DNS profile and getting this output:

> Exception in heartbeat_loop: Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
>     return await self.task
> asyncio.exceptions.CancelledError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/mythic_c2_container/mythic_service.py", line 498, in heartbeat_loop
>     connection = await aio_pika.connect_robust(
>   File "/usr/local/lib/python3.8/site-packages/aio_pika/robust_connection.py", line 271, in connect_robust
>     return await connect(
>   File "/usr/local/lib/python3.8/site-packages/aio_pika/connection.py", line 333, in connect
>     await connection.connect(
>   File "/usr/local/lib/python3.8/site-packages/aio_pika/robust_connection.py", line 127, in connect
>     result = await super().connect(
>   File "/usr/local/lib/python3.8/site-packages/aio_pika/connection.py", line 120, in connect
>     self.connection = await asyncio.wait_for(
>   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
>     return await fut
>   File "/usr/local/lib/python3.8/site-packages/aio_pika/connection.py", line 105, in _make_connection
>     connection = await aiormq.connect(self.url, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/aiormq/connection.py", line 542, in connect
>     await connection.connect(client_properties or {})
>   File "/usr/local/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
>     return await self.create_task(func(self, *args, **kwargs))
>   File "/usr/local/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
>     raise self.exception from e
> aiormq.exceptions.ProbableAuthenticationError: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.

**Comment by its-a-feature** [comment]
The dns profile isn't updated for Mythic 3 since no agent uses it. I'll get it updated soon though

**Comment by its-a-feature** [comment]
I'm running on macOS Ventura on Intel though, so I wonder if there's maybe an issue with orbstack and Sonoma since it just came out?

**Comment by its-a-feature** [comment]
I won't be able to test on a sonoma arm machine until next week. are you able to deploy on something else until then?

**Comment by ts-lbf** [comment]
Yes, i might be able to find a workaround until then. Thanks for the quick response, looking forward to hear more

**Comment by its-a-feature** [comment]
Just ran it without issue on my M1 mac with Sonoma 🤔 Can you do `ls -alhO@` for the directory where Mythic is running? That will allow me to see if there's potentially any weird files or weird attributes on files that might be causing an issue.

**Comment by ts-lbf** [comment]
I just got the 3.1.0 version of Mythic and now I am encountering other issues. I think i will resolve to running it on another box. 
Thanks for the good support tho!
