### ISSUE TITLE
Hosting payload via C2 HTTP profile breaks http profile configuration.

### ISSUE THREAD

**Issue by timukas** [MythicC2Profiles/http#14]
Hello,

Go to Payloads, click 'Details' next to any generated payload, then click on the 'Globe' icon.
On popup pick http profile and set some name:
 

![image](https://github.com/MythicC2Profiles/http/assets/1915618/0dd90233-cc41-4805-a39d-89474c7670a7)

After submitting it, main http profile configuration has new payload block, but missing ServerHeaders part

![image](https://github.com/MythicC2Profiles/http/assets/1915618/160a5128-c86c-486e-b3d0-08deee0c3a1e)

P.s. websocket profile works fine, no configuration is being removed.

**Comment by its-a-feature** [comment]
Good catch! I just made a push for it. The internal structure was missing the ServerHeaders field

**Comment by its-a-feature** [comment]
If that doesn't fix your issue, please feel free to re-open this issue and provide more context as to what you're seeing
